"""MoodScape — Guided Meditation Audio Generator (Gradio UI)."""

import os
import time
import queue
import threading
import warnings

# Prevent HuggingFace tokenizers from warning about fork-after-parallelism.
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

# keras (indextts dep) and tensorboard ship _pb2.py files generated by old protoc.
# Those files call descriptor.Descriptor() directly, which fails with the protobuf
# C extension in protobuf >=4.x. Force pure-Python mode unconditionally — this must
# be set before ANY google.protobuf import, including transitive ones.
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

# Fix: MacOS Bus Error (SIGBUS) when Python garbage collects MPS tensors on process exit.
# We disable fallback to prevent unsupported ops from quietly failing, and register
# a hard exit hook to bypass the problematic PyTorch C++ destructor sequence.
os.environ.setdefault("PYTORCH_ENABLE_MPS_FALLBACK", "1")
os.environ.setdefault("PYTORCH_MPS_HIGH_WATERMARK_RATIO", "0.0")
import atexit
atexit.register(lambda: os._exit(0))

# Silence noisy third-party warnings that are not actionable from user code.
warnings.filterwarnings(
    "ignore",
    message="To copy construct from a tensor",
    category=UserWarning,
    module="transformers",
)
warnings.filterwarnings(
    "ignore",
    message="Possible clipped samples in output",
    category=UserWarning,
    module="pyloudnorm",
)
# PyTorch's elastic distributed multiprocessing prints an "unsupported on macOS"
# note at import time — harmless on single-process MPS/MLX workloads.
warnings.filterwarnings(
    "ignore",
    message=".*Redirects are currently not supported.*",
)

# torchao tries to import a CUDA-only triton integer-matmul kernel on startup and
# prints "import error: No module named 'triton'" when it's absent (Apple Silicon).
# The model falls back gracefully; pre-importing with stdout redirected hides the
# cosmetic message without affecting behaviour.
import contextlib, io as _io
with contextlib.redirect_stdout(_io.StringIO()):
    try:
        import torchao  # noqa: F401
    except ImportError:
        pass

import numpy as np
import soundfile as sf
import gradio as gr
from dotenv import load_dotenv

from core.kokoro_tts.engine import KokoroEngine
from core.pipeline import MeditationPipeline
from core.f5_tts import voice_registry as _f5_registry
from core.index_tts import voice_registry as _indextts_registry

# Load environment variables (like HF_TOKEN) from .env file
load_dotenv()

# ── F5-TTS voice registry (scanned at startup) ───────────────────────────────

_F5_VOICE_REGISTRY = _f5_registry.scan()
# Slug list for the dropdown; sorted alphabetically for consistent ordering.
F5_VOICE_SLUGS = sorted(_F5_VOICE_REGISTRY.keys())
# (label, value) pairs — label is human-readable, value is the slug for the pipeline.
F5_VOICE_CHOICES = [(slug.replace("_", " ").title(), slug) for slug in F5_VOICE_SLUGS]
F5_VOICE_DEFAULT = F5_VOICE_CHOICES[0][1] if F5_VOICE_CHOICES else None

# ── IndexTTS-2 voice and emotion registries (scanned at startup) ──────────────

_INDEXTTS_VOICE_REGISTRY = _indextts_registry.scan_voices()
INDEXTTS_VOICE_SLUGS = sorted(_INDEXTTS_VOICE_REGISTRY.keys())
INDEXTTS_VOICE_CHOICES = [(slug.replace("_", " ").title(), slug) for slug in INDEXTTS_VOICE_SLUGS]
INDEXTTS_VOICE_DEFAULT = INDEXTTS_VOICE_CHOICES[0][1] if INDEXTTS_VOICE_CHOICES else None

_INDEXTTS_EMOTION_REGISTRY = _indextts_registry.scan_emotions()
INDEXTTS_EMOTION_SLUGS = sorted(_INDEXTTS_EMOTION_REGISTRY.keys())
INDEXTTS_EMOTION_CHOICES = [("None (neutral)", "")] + [(slug.replace("_", " ").title(), slug) for slug in INDEXTTS_EMOTION_SLUGS]
INDEXTTS_EMOTION_DEFAULT = INDEXTTS_EMOTION_CHOICES[0][1]

# ── Voice choices for Kokoro engine ──────────────────────────────────────────

# (label, voice_id) pairs shown in the Kokoro dropdown.
# Presets resolve to blended voice tensors via core.kokoro_tts.voice_manager.
KOKORO_VOICE_CHOICES = [
    # Premium Blends (Recommended)
    ("Balanced Calm — natural & human (default)",  "balanced_calm"),
    ("Deep Rest — intimate & breathy",             "deep_rest"),
    ("Soft Whisper — ASMR relaxation",             "soft_whisper"),
    ("Golden Hour — warm & airy",                  "golden_hour"),
    ("Earth Root — grounding blend",               "earth_root"),
    ("Pure Calm — tension-free ultra-soft",        "pure_calm"),
    # High-Quality Individual Voices
    ("Heart — US Female (warm)",                 "af_heart"),
    ("Nicole — US Female (calm/ASMR)",           "af_nicole"),
    # British & Male Voices
    ("Emma — UK Female (wise)",                  "bf_emma"),
    ("Adam — US Male (grounding)",               "am_adam"),
    ("George — UK Male (warm)",                  "bm_george"),
]

pipeline = MeditationPipeline()

DEFAULT_SCRIPT = """\
Welcome to this guided meditation. [pause:3s]

Find a comfortable position... and gently close your eyes. [pause:5s]

Take a slow, deep breath in... [pause:4s] and release. [pause:6s]

Notice the sensations in your body. [pause:8s]

With each breath, allow yourself to sink deeper into relaxation. [pause:5s]

There is nowhere else you need to be. Nothing else you need to do. [pause:6s]

Simply be here, in this moment. [pause:10s]

When you are ready, gently bring your awareness back to the room. [pause:5s]

Slowly open your eyes. Thank you for practicing with me today. [pause:3s]\
"""

DEFAULT_MUSIC_PROMPT = (
    "ambient, warm synthesizer pads, gentle drone, slow evolving, "
    "spacious atmosphere, peaceful, soft sustained tones, new age"
)


def _get_duration(path: str) -> float:
    info = sf.info(path)
    return info.duration


def _render_status(message, fraction, detail="", elapsed=None):
    percent = int(fraction * 100)
    elapsed_html = ""
    if elapsed is not None:
        m = int(elapsed // 60)
        s = int(elapsed % 60)
        elapsed_str = f"{m}:{s:02d}" if m > 0 else f"{s}s"
        elapsed_html = f'<span class="status-elapsed">{elapsed_str}</span>'

    if fraction >= 1.0:
        return f"""
        <div class="status-shell">
            <div class="status-complete">
                <span class="status-check">&#10003;</span>
                <span class="status-msg">{message}</span>
                {elapsed_html}
            </div>
            {f'<div class="status-detail">{detail}</div>' if detail else ''}
        </div>
        """
    elif fraction <= 0 and ("Error" in message or "Failed" in message):
        return f"""
        <div class="status-shell">
            <div class="status-bar">
                <span class="status-msg status-error">{message}</span>
                {elapsed_html}
            </div>
            {f'<div class="status-detail status-error">{detail}</div>' if detail else ''}
        </div>
        """
    else:
        return f"""
        <div class="status-shell">
            <div class="status-bar">
                <span class="status-msg">{message}</span>
                <span class="status-right">
                    <span class="status-pct">{percent}%</span>
                    {elapsed_html}
                </span>
            </div>
            <div class="progress-track">
                <div class="progress-fill" style="width: {percent}%"></div>
            </div>
            {f'<div class="status-detail">{detail}</div>' if detail else ''}
        </div>
        """


def generate_meditation(
    generation_mode,
    script,
    music_prompt,
    music_duration,
    music_model_choice,
    kokoro_voice,
    speed,
    duck_amount,
    reverb_amount,
    fade_in,
    fade_out,
    output_format,
    seed_value,
    export_stems_flag,
    upsample_flag,
    stem_separation_flag,
    reference_audio_file,
    acestep_quality,
    acestep_bpm,
    acestep_key,
    lyria_bpm,
    lyria_density,
    lyria_brightness,
    tts_engine_choice,
    f5_voice_slug,
    f5_wpm,
    reverb_ir_choice,
    quality_mode_flag,
    stereo_output_flag,
    indextts_voice_slug,
    indextts_emotion_slug,
    indextts_emotion_audio_file,
    indextts_speed,
    uploaded_music_file,
):
    # Initial status
    yield None, _render_status("Initializing Pipeline", 0.0)

    # Map music model label to engine key
    if music_model_choice == "ACE-Step 1.5":
        music_model = "acestep"
    elif music_model_choice == "Lyria RealTime":
        music_model = "lyria"
        # Validate that the API key is available before launching the pipeline
        if not os.environ.get("GOOGLE_API_KEY", "").strip():
            yield None, _render_status("Error: GOOGLE_API_KEY missing", 0.0, "Please check your .env file")
            return
    elif music_model_choice == "Upload File":
        music_model = "upload"
        # Validate that an instrumental file was provided and is a supported format.
        if not uploaded_music_file:
            yield None, _render_status(
                "Error: No instrumental uploaded", 0.0,
                "Upload an instrumental file or pick a different music engine.",
            )
            return
        _ext = os.path.splitext(uploaded_music_file)[1].lower()
        if _ext not in {".wav", ".mp3", ".flac", ".ogg", ".m4a", ".aiff", ".aif"}:
            yield None, _render_status(
                f"Error: Unsupported audio format '{_ext}'", 0.0,
                "Supported: wav, mp3, flac, ogg, m4a, aiff, aif.",
            )
            return

    # Resolve seed: 0 means auto
    seed = int(seed_value) if seed_value and int(seed_value) != 0 else None

    # Map quality label to engine key (Task 5)
    # "Draft (Turbo / 8-step)" -> "turbo"
    # "Studio (SFT / 50-step)" -> "sft"
    acestep_model_type = "turbo" if "Turbo" in acestep_quality else "sft"

    # Map TTS engine label to key
    if tts_engine_choice == "F5-TTS":
        tts_engine = "f5"
    elif tts_engine_choice == "IndexTTS-2":
        tts_engine = "indextts"
    else:
        tts_engine = "kokoro"

    # Queue for streaming progress updates from the pipeline thread.
    # Items are (fraction, message) tuples; None is the sentinel for completion.
    update_queue = queue.Queue()
    result_container = {}
    start_time = time.time()

    def progress_cb(fraction, message):
        update_queue.put((fraction, message))

    def run_pipeline():
        try:
            result = pipeline.generate(
                generation_mode=generation_mode,
                script=script,
                music_prompt=music_prompt,
                instrumental_duration_m=music_duration,
                voice=kokoro_voice,
                speed=speed,
                music_model=music_model,
                duck_amount_db=duck_amount,
                reverb_amount=reverb_amount,
                fade_in_sec=fade_in,
                fade_out_sec=fade_out,
                output_format=output_format,
                progress_cb=progress_cb,
                seed=seed,
                do_export_stems=export_stems_flag,
                upsample_48k=upsample_flag,
                stem_separation=stem_separation_flag,
                bpm=acestep_bpm,
                keyscale=acestep_key,
                acestep_model_type=acestep_model_type,
                lyria_bpm=int(lyria_bpm),
                lyria_density=float(lyria_density),
                lyria_brightness=float(lyria_brightness),
                tts_engine=tts_engine,
                f5_voice_slug=f5_voice_slug if tts_engine == "f5" else None,
                f5_target_wpm=int(f5_wpm) if tts_engine == "f5" and f5_wpm > 0 else None,
                indextts_voice_slug=indextts_voice_slug if tts_engine == "indextts" else None,
                indextts_emotion_slug=indextts_emotion_slug if tts_engine == "indextts" and indextts_emotion_slug else None,
                indextts_emotion_audio_path=indextts_emotion_audio_file if tts_engine == "indextts" and indextts_emotion_audio_file else None,
                indextts_speed=float(indextts_speed) if tts_engine == "indextts" else 1.0,
                reverb_ir=reverb_ir_choice,
                quality_mode=bool(quality_mode_flag),
                stereo_output=bool(stereo_output_flag),
                melody_audio_path=reference_audio_file or None,
                uploaded_music_path=uploaded_music_file or None,
            )
            result_container["result"] = result
        except Exception as e:
            result_container["error"] = str(e)
        finally:
            update_queue.put(None)  # sentinel: pipeline finished

    thread = threading.Thread(target=run_pipeline, daemon=True)
    thread.start()

    # Stream progress updates until the pipeline signals done
    current_fraction = 0.0
    current_message = "Starting..."
    while True:
        try:
            item = update_queue.get(timeout=0.25)
        except queue.Empty:
            # No new update yet — re-yield current state with fresh elapsed time
            elapsed = time.time() - start_time
            yield None, _render_status(current_message, current_fraction, elapsed=elapsed)
            continue

        if item is None:
            break  # Pipeline finished

        current_fraction, current_message = item
        elapsed = time.time() - start_time
        yield None, _render_status(current_message, current_fraction, elapsed=elapsed)

    thread.join()
    elapsed = time.time() - start_time

    if "error" in result_container:
        yield None, _render_status("Generation Failed", 0.0, result_container["error"], elapsed=elapsed)
        return

    output_path, status_msg, _ = result_container["result"]
    duration = _get_duration(output_path)
    minutes = int(duration // 60)
    seconds = int(duration % 60)
    tts_label = {"f5": "F5-TTS", "kokoro": "Kokoro", "indextts": "IndexTTS-2"}.get(tts_engine, "Kokoro")
    detail = f"Synthesized with {tts_label} + {music_model_choice} · {minutes}m {seconds}s"
    yield output_path, _render_status("Generation Complete", 1.0, detail, elapsed=elapsed)


# ── Design System: "Sumi & Amber" ──────────────────────────────────────────
# Warm monastic minimalism. Cormorant Garamond display serif + DM Sans body.
# Palette: warm near-black + amber gold + sage. No purple gradients, no glass.
CUSTOM_CSS = """
/* ── FONTS ─────────────────────────────────────────────────────── */
@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500;1,600&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300&family=JetBrains+Mono:wght@400;500&display=swap');

/* ── DESIGN TOKENS ──────────────────────────────────────────────── */
:root {
    /* Backgrounds — warm charcoal, not cool grey */
    --bg:              #0d0c09;
    --surface-lo:      #141210;
    --surface:         #1a1815;
    --surface-hi:      #232019;
    --surface-raised:  #2d2921;

    /* Amber — candlelight, meditation bell, brass singing bowl */
    --amber:           #c4a05c;
    --amber-bright:    #deba7a;
    --amber-dim:       #8a6e3e;
    --amber-muted:     rgba(196, 160, 92, 0.14);
    --amber-glow:      rgba(196, 160, 92, 0.06);
    --amber-border:    rgba(196, 160, 92, 0.16);
    --amber-border-hi: rgba(196, 160, 92, 0.38);

    /* Sage — forest floor, fresh air */
    --sage:            #6b8a72;
    --sage-muted:      rgba(107, 138, 114, 0.18);

    /* Text */
    --text-1:          #ece6d8;
    --text-2:          #ada69a;
    --text-3:          #716960;
    --text-4:          #403c36;

    /* Semantic */
    --error:           #c97b67;
    --success:         #7fa882;

    /* Typography */
    --font-display: 'Cormorant Garamond', 'Palatino Linotype', Georgia, serif;
    --font-body:    'DM Sans', system-ui, -apple-system, sans-serif;
    --font-mono:    'JetBrains Mono', 'Fira Code', ui-monospace, monospace;

    /* Geometry */
    --r-xs: 3px;
    --r-sm: 6px;
    --r-md: 10px;
    --r-lg: 16px;

    /* Motion */
    --ease: cubic-bezier(0.4, 0, 0.2, 1);
    --t-fast: 150ms;
    --t-base: 220ms;
    --t-slow: 400ms;
}

/* ── RESET & BASE ────────────────────────────────────────────────── */
*, *::before, *::after { box-sizing: border-box; }

body {
    background: var(--bg) !important;
    color: var(--text-1) !important;
    font-family: var(--font-body) !important;
}

.gradio-container {
    font-family: var(--font-body) !important;
    background: var(--bg) !important;
    min-height: 100vh !important;
}

/* ── HEADER ──────────────────────────────────────────────────────── */
.app-header {
    padding: 3rem 0 2rem;
    border-bottom: 1px solid var(--amber-border);
    margin-bottom: 2rem;
}

.app-header-inner {
    display: flex;
    align-items: center;
    gap: 2rem;
}

/* Breathing orb — the signature element */
.breath-orb {
    position: relative;
    width: 52px;
    height: 52px;
    flex-shrink: 0;
}

.breath-ring {
    position: absolute;
    inset: 0;
    border: 1px solid var(--amber);
    border-radius: 50%;
    animation: breathe 7s ease-in-out infinite;
}

.breath-ring--2 {
    animation-delay: -3.5s;
    border-color: var(--sage);
    opacity: 0.5;
}

@keyframes breathe {
    0%, 100% { transform: scale(0.65); opacity: 0.55; }
    50%       { transform: scale(1.0);  opacity: 0.12; }
}

.app-header-text { display: flex; flex-direction: column; gap: 0.35rem; }

.app-wordmark {
    font-family: var(--font-display) !important;
    font-size: 3.6rem !important;
    font-weight: 600 !important;
    font-style: italic !important;
    color: var(--amber) !important;
    letter-spacing: -0.01em !important;
    line-height: 1 !important;
    margin: 0 !important;
}

.app-tagline {
    font-family: var(--font-body) !important;
    font-size: 0.72rem !important;
    font-weight: 300 !important;
    color: var(--text-3) !important;
    letter-spacing: 0.18em !important;
    text-transform: uppercase !important;
    margin: 0 !important;
}

/* ── CANVAS ZONE (left column) ───────────────────────────────────── */
.canvas-zone {
    background: var(--surface-lo) !important;
    border: 1px solid var(--amber-border) !important;
    border-radius: var(--r-lg) !important;
    padding: 1.75rem !important;
}

/* ── SETTINGS SIDEBAR (right column) ─────────────────────────────── */
.settings-sidebar {
    background: transparent !important;
    border: none !important;
    padding: 0 !important;
}

/* ── MODE SELECTOR: PILL RADIO ───────────────────────────────────── */
.pill-radio .wrap {
    display: flex !important;
    gap: 2px !important;
    background: var(--surface-lo) !important;
    border: 1px solid var(--amber-border) !important;
    border-radius: var(--r-xs) !important;
    padding: 3px !important;
}

.pill-radio label {
    flex: 1 !important;
    text-align: center !important;
    padding: 9px 14px !important;
    border-radius: 2px !important;
    font-family: var(--font-body) !important;
    font-size: 0.78rem !important;
    font-weight: 400 !important;
    letter-spacing: 0.04em !important;
    color: var(--text-3) !important;
    cursor: pointer !important;
    transition: all var(--t-base) var(--ease) !important;
    border: none !important;
    background: transparent !important;
}

.pill-radio label.selected,
.pill-radio label:has(input:checked) {
    background: var(--amber-muted) !important;
    color: var(--amber) !important;
}

.pill-radio input[type="radio"] { display: none !important; }

/* ── ACCORDION SECTIONS ──────────────────────────────────────────── */
.accordion-section {
    border: none !important;
    border-radius: 0 !important;
    background: transparent !important;
    margin-bottom: 0 !important;
    overflow: visible !important;
    border-bottom: 1px solid var(--amber-border) !important;
}

.accordion-section:last-of-type {
    border-bottom: none !important;
}

.accordion-section > .label-wrap {
    padding: 14px 0 !important;
    font-family: var(--font-body) !important;
    font-weight: 400 !important;
    font-size: 0.7rem !important;
    letter-spacing: 0.12em !important;
    text-transform: uppercase !important;
    color: var(--text-3) !important;
    background: transparent !important;
    border: none !important;
}

.accordion-section > .label-wrap:hover {
    color: var(--text-2) !important;
}

.accordion-section > .content {
    padding: 0 0 18px 0 !important;
}

/* ── TEXTAREAS ───────────────────────────────────────────────────── */
textarea {
    background: var(--surface) !important;
    border: 1px solid var(--amber-border) !important;
    border-radius: var(--r-sm) !important;
    padding: 16px 18px !important;
    color: var(--text-1) !important;
    font-family: var(--font-body) !important;
    font-size: 0.95rem !important;
    line-height: 1.75 !important;
    transition: border-color var(--t-base) var(--ease),
                box-shadow var(--t-base) var(--ease),
                background var(--t-base) var(--ease) !important;
    resize: vertical !important;
}

textarea:focus {
    border-color: var(--amber-border-hi) !important;
    box-shadow: 0 0 0 3px var(--amber-glow) !important;
    background: var(--surface-hi) !important;
    outline: none !important;
}

textarea::placeholder {
    color: var(--text-4) !important;
    font-style: italic !important;
}

/* ── TEXT & NUMBER INPUTS ────────────────────────────────────────── */
input[type="text"],
input[type="number"] {
    background: var(--surface) !important;
    border: 1px solid var(--amber-border) !important;
    border-radius: var(--r-sm) !important;
    padding: 8px 12px !important;
    color: var(--text-1) !important;
    font-family: var(--font-mono) !important;
    font-size: 0.84rem !important;
    transition: border-color var(--t-base) var(--ease) !important;
}

input[type="text"]:focus,
input[type="number"]:focus {
    border-color: var(--amber-border-hi) !important;
    box-shadow: 0 0 0 3px var(--amber-glow) !important;
    outline: none !important;
}

/* ── DROPDOWNS ───────────────────────────────────────────────────── */
.gradio-dropdown {
    background: var(--surface) !important;
    border: 1px solid var(--amber-border) !important;
    border-radius: var(--r-sm) !important;
    transition: border-color var(--t-base) var(--ease) !important;
}

.gradio-dropdown:focus-within {
    border-color: var(--amber-border-hi) !important;
    box-shadow: 0 0 0 3px var(--amber-glow) !important;
}

/* ── GENERATE BUTTON ─────────────────────────────────────────────── */
.primary-btn button,
.primary-btn {
    background: var(--amber) !important;
    border: none !important;
    border-radius: var(--r-sm) !important;
    font-family: var(--font-body) !important;
    font-weight: 500 !important;
    font-size: 0.82rem !important;
    letter-spacing: 0.1em !important;
    text-transform: uppercase !important;
    padding: 15px 28px !important;
    color: var(--bg) !important;
    cursor: pointer !important;
    transition: background var(--t-base) var(--ease),
                box-shadow var(--t-base) var(--ease),
                transform var(--t-fast) var(--ease) !important;
    width: 100% !important;
}

.primary-btn button:hover,
.primary-btn:hover {
    background: var(--amber-bright) !important;
    box-shadow: 0 2px 20px rgba(196, 160, 92, 0.28) !important;
}

.primary-btn button:active,
.primary-btn:active {
    transform: translateY(1px) !important;
    box-shadow: none !important;
}

/* ── AUDIO PLAYER ────────────────────────────────────────────────── */
.music-player-glass {
    background: var(--surface-hi) !important;
    border: 1px solid var(--amber-border) !important;
    border-radius: var(--r-md) !important;
    padding: 14px !important;
    margin-top: 14px !important;
}

/* ── SLIDERS ─────────────────────────────────────────────────────── */
input[type="range"] {
    accent-color: var(--amber) !important;
}

/* ── LABELS ──────────────────────────────────────────────────────── */
.block-label,
.block-title {
    font-family: var(--font-body) !important;
    font-weight: 400 !important;
    font-size: 0.68rem !important;
    color: var(--text-3) !important;
    text-transform: uppercase !important;
    letter-spacing: 0.1em !important;
}

/* ── STATUS DISPLAY ──────────────────────────────────────────────── */
.status-shell {
    padding: 10px 0 0;
    border-top: 1px solid var(--amber-border);
    margin-top: 6px;
}

.status-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.status-msg {
    font-family: var(--font-body);
    font-size: 0.78rem;
    font-weight: 400;
    color: var(--text-2);
    letter-spacing: 0.02em;
}

.status-right {
    display: flex;
    align-items: center;
    gap: 10px;
}

.status-pct {
    font-family: var(--font-mono);
    font-size: 0.78rem;
    color: var(--amber);
    font-weight: 500;
}

.status-elapsed {
    font-family: var(--font-mono);
    font-size: 0.72rem;
    color: var(--text-3);
}

/* Hair-thin progress line — deliberate restraint */
.progress-track {
    width: 100%;
    height: 1px;
    background: var(--amber-border);
    margin: 10px 0 5px;
    position: relative;
    overflow: visible;
}

.progress-fill {
    height: 100%;
    background: var(--amber);
    box-shadow: 0 0 6px rgba(196, 160, 92, 0.6);
    transition: width 0.45s var(--ease);
    position: relative;
}

/* Leading dot on the progress line */
.progress-fill::after {
    content: '';
    position: absolute;
    right: -1px;
    top: 50%;
    transform: translateY(-50%);
    width: 5px;
    height: 5px;
    border-radius: 50%;
    background: var(--amber);
    box-shadow: 0 0 8px rgba(196, 160, 92, 0.8);
}

.status-detail {
    font-size: 0.72rem;
    color: var(--text-3);
    font-family: var(--font-mono);
    margin-top: 5px;
    letter-spacing: 0.02em;
}

.status-complete {
    display: flex;
    align-items: center;
    gap: 8px;
}

.status-check {
    color: var(--success);
    font-size: 0.85rem;
    font-weight: 500;
}

.status-complete .status-msg {
    color: var(--text-2);
}

.status-error {
    color: var(--error) !important;
}

/* ── MARKDOWN INSIDE ACCORDIONS ──────────────────────────────────── */
.accordion-section h4 {
    font-family: var(--font-body) !important;
    font-size: 0.68rem !important;
    font-weight: 400 !important;
    color: var(--text-3) !important;
    letter-spacing: 0.12em !important;
    text-transform: uppercase !important;
    margin: 1.25rem 0 0.75rem !important;
    padding-top: 0.75rem !important;
    border-top: 1px solid var(--amber-border) !important;
}

/* ── CHECKBOXES ──────────────────────────────────────────────────── */
.toggle-switch input[type="checkbox"] {
    accent-color: var(--amber) !important;
}

/* ── SECTION SPACING ─────────────────────────────────────────────── */
.dropdown-container {
    margin-bottom: 0.6rem !important;
}

/* ── INFO TEXT ───────────────────────────────────────────────────── */
.gr-info, .info {
    color: var(--text-3) !important;
    font-family: var(--font-body) !important;
    font-size: 0.72rem !important;
}

/* ── SCROLLBAR ───────────────────────────────────────────────────── */
::-webkit-scrollbar { width: 5px; }
::-webkit-scrollbar-track { background: var(--bg); }
::-webkit-scrollbar-thumb {
    background: var(--amber-border);
    border-radius: 3px;
}
::-webkit-scrollbar-thumb:hover {
    background: var(--amber-dim);
}
"""

DROPDOWN_FIX_JS = """
() => {
    // Fix 1: Toggle-close — prevent re-opening when clicking an already-open dropdown
    document.addEventListener('mousedown', function(e) {
        const wrapInner = e.target.closest('.wrap-inner');
        if (!wrapInner) return;
        const wrap = wrapInner.closest('.wrap');
        if (!wrap) return;
        const input = wrap.querySelector('input');
        if (input && input === document.activeElement) {
            e.preventDefault();   // stop click from re-focusing
            input.blur();         // close the dropdown
        }
    }, true);  // capture phase

    // Fix 2: Close all open dropdowns on page scroll
    window.addEventListener('scroll', function() {
        document.querySelectorAll('.wrap input:focus').forEach(function(input) {
            input.blur();
        });
    }, { passive: true });
}
"""

theme = gr.themes.Base(
    primary_hue="stone",
    secondary_hue="stone",
    neutral_hue="stone",
    font=[
        gr.themes.GoogleFont("DM Sans"),
        "ui-sans-serif", "system-ui", "sans-serif",
    ],
    font_mono=[gr.themes.GoogleFont("JetBrains Mono"), "ui-monospace", "monospace"],
).set(
    body_background_fill="#0d0c09",
    body_text_color="#ece6d8",
    body_text_color_subdued="#ada69a",
    block_background_fill="#1a1815",
    block_border_color="rgba(196,160,92,0.16)",
    block_border_width="1px",
    block_label_text_color="#716960",
    block_label_background_fill="transparent",
    block_title_text_weight="400",
    block_title_text_size="11px",
    block_title_text_color="#716960",
    input_background_fill="#141210",
    input_border_color="rgba(196,160,92,0.16)",
    input_border_color_focus="#c4a05c",
    input_placeholder_color="#403c36",
    button_primary_background_fill="#c4a05c",
    button_primary_background_fill_hover="#deba7a",
    button_primary_text_color="#0d0c09",
    button_primary_border_color="transparent",
    button_secondary_background_fill="#1a1815",
    button_secondary_border_color="rgba(196,160,92,0.16)",
    button_secondary_text_color="#ada69a",
).set(
    body_background_fill_dark="#0d0c09",
    block_background_fill_dark="#1a1815",
    input_background_fill_dark="#141210",
)

# ── Build the Gradio UI ────────────────────────────────────────────────────

with gr.Blocks(
    title="MoodScape — Guided Meditation Generator",
) as demo:

    gr.HTML("""
        <div class="app-header">
            <div class="app-header-inner">
                <div class="breath-orb" title="Inhale… exhale…">
                    <div class="breath-ring"></div>
                    <div class="breath-ring breath-ring--2"></div>
                </div>
                <div class="app-header-text">
                    <h1 class="app-wordmark">MoodScape</h1>
                    <p class="app-tagline">Guided Meditation Synthesis</p>
                </div>
            </div>
        </div>
    """)

    with gr.Row():
        # ── Left column: Creative Canvas ──────────────────────────────────
        with gr.Column(scale=3, elem_classes="canvas-zone"):
            with gr.Group():
                generation_mode = gr.Radio(
                    choices=["Instrumental Only", "Vocals Only", "Instrumental + Vocal"],
                    value="Instrumental + Vocal",
                    label="Mode",
                    elem_classes="pill-radio",
                )
                script_input = gr.Textbox(
                    label="Meditation Script",
                    placeholder=(
                        "Write your meditation script here…\n"
                        "Use [pause:5s] for timed pauses, [breath] for breath cues.\n"
                        "Double newlines create natural phrase gaps."
                    ),
                    value=DEFAULT_SCRIPT,
                    lines=14,
                    elem_id="script-textbox",
                )

            with gr.Row():
                music_prompt = gr.Textbox(
                    label="Atmosphere",
                    placeholder="E.g. warm synthesizer pads, gentle rain, minimal soft piano…",
                    value=DEFAULT_MUSIC_PROMPT,
                    lines=2,
                    scale=2,
                )
                music_duration = gr.Slider(
                    minimum=1.0,
                    maximum=30.0,
                    value=3.0,
                    step=0.5,
                    label="Duration (min)",
                    visible=False,
                    scale=1,
                )

            generate_btn = gr.Button(
                "Generate Meditation",
                variant="primary",
                size="lg",
                elem_classes="primary-btn",
            )
            audio_output = gr.Audio(
                label="Your Meditation",
                type="filepath",
                elem_classes="music-player-glass",
            )
            status_display = gr.HTML(
                _render_status("Ready", 0.0, "Ready to synthesize."),
                elem_id="status-display",
            )

        # ── Right column: Settings Sidebar ────────────────────────────────
        with gr.Column(scale=2, elem_classes="settings-sidebar"):

            # Section 1: Voice & Sound
            with gr.Accordion("Voice & Sound", open=True, elem_classes="accordion-section"):
                music_model_dropdown = gr.Dropdown(
                    choices=["ACE-Step 1.5", "Lyria RealTime", "Upload File"],
                    value="ACE-Step 1.5",
                    label="Music Engine",
                    info="ACE-Step 1.5 recommended for Apple Silicon (~5 min). Choose Upload File to bring your own instrumental.",
                    elem_classes="dropdown-container",
                )
                acestep_quality = gr.Radio(
                    choices=["Draft (Turbo / 8-step)", "Studio (SFT / 50-step)"],
                    value="Studio (SFT / 50-step)",
                    label="Quality",
                    visible=True,
                    elem_classes="pill-radio",
                )
                tts_engine_radio = gr.Radio(
                    choices=["Kokoro", "F5-TTS", "IndexTTS-2"],
                    value="Kokoro",
                    label="Voice Engine",
                    elem_classes="pill-radio",
                )
                with gr.Group(visible=True, elem_id="kokoro-group") as kokoro_settings:
                    kokoro_voice_dropdown = gr.Dropdown(
                        choices=KOKORO_VOICE_CHOICES,
                        value="balanced_calm",
                        label="Voice",
                        elem_classes="dropdown-container",
                    )
                with gr.Group(visible=False, elem_id="f5-group") as f5_settings:
                    f5_voice_dropdown = gr.Dropdown(
                        choices=F5_VOICE_CHOICES if F5_VOICE_CHOICES else ["(no voices)"],
                        value=F5_VOICE_DEFAULT,
                        label="Voice",
                        interactive=bool(F5_VOICE_CHOICES),
                        elem_classes="dropdown-container",
                    )
                    f5_wpm_slider = gr.Slider(
                        0, 150, 0, step=5,
                        label="Pacing (WPM)",
                        info="0 = natural rhythm (recommended). 90–110 = meditation. 120–150 = narration.",
                    )
                with gr.Group(visible=False, elem_id="indextts-group") as indextts_settings:
                    indextts_voice_dropdown = gr.Dropdown(
                        choices=INDEXTTS_VOICE_CHOICES if INDEXTTS_VOICE_CHOICES else ["(no voices — add .wav to assets/speakers/reference_audio/)"],
                        value=INDEXTTS_VOICE_DEFAULT,
                        label="Voice",
                        interactive=bool(INDEXTTS_VOICE_CHOICES),
                        elem_classes="dropdown-container",
                    )
                    indextts_emotion_dropdown = gr.Dropdown(
                        choices=INDEXTTS_EMOTION_CHOICES,
                        value=INDEXTTS_EMOTION_DEFAULT,
                        label="Emotion Preset",
                        elem_classes="dropdown-container",
                        info="Choose an emotion preset or upload a custom reference below.",
                    )
                    indextts_emotion_audio = gr.Audio(
                        label="Custom Emotion Reference (optional)",
                        type="filepath",
                        sources=["upload"],
                    )
                    indextts_speed_slider = gr.Slider(
                        0.70, 1.30, 1.0, step=0.05,
                        label="Speaking Speed",
                        info="IndexTTS-2 pacing is controlled by emotion preset + pause durations; this slider is inactive.",
                        interactive=False,
                    )

            # Section 2: Mix & Effects
            with gr.Accordion("Mix & Effects", open=False, elem_classes="accordion-section"):
                with gr.Row():
                    speed_slider = gr.Slider(0.70, 1.20, 0.9, step=0.01, label="Speech Speed", info="0.85–0.95 is ideal for guided meditation.")
                    duck_slider = gr.Slider(-30, -5, -8, step=1, label="Music Ducking (dB)", info="How much music dims under voice.")
                with gr.Row():
                    reverb_slider = gr.Slider(0.0, 0.5, 0.15, step=0.05, label="Reverb Amount")
                    reverb_ir_dropdown = gr.Dropdown(
                        choices=[
                            ("Warm Studio", "warm_studio"),
                            ("Wooden Hall", "wooden_hall"),
                            ("Stone Chapel", "stone_chapel"),
                        ],
                        value="warm_studio",
                        label="Space / IR",
                        elem_classes="dropdown-container",
                    )
                with gr.Row():
                    fade_in_slider = gr.Slider(0, 10, 3, step=0.5, label="Fade In (s)")
                    fade_out_slider = gr.Slider(0, 15, 6, step=0.5, label="Fade Out (s)")

            # Section 3: Advanced
            with gr.Accordion("Advanced", open=False, elem_classes="accordion-section"):
                with gr.Group(visible=True) as acestep_metadata:
                    gr.Markdown("#### ACE-Step Tuning")
                    with gr.Row():
                        acestep_bpm = gr.Slider(40, 100, 50, step=1, label="BPM")
                        acestep_key = gr.Dropdown(
                            choices=["Auto", "C Major", "C Minor", "C# Major", "C# Minor", "D Major", "D Minor", "Eb Major", "Eb Minor", "E Major", "E Minor", "F Major", "F Minor", "F# Major", "F# Minor", "G Major", "G Minor", "Ab Major", "Ab Minor", "A Major", "A Minor", "Bb Major", "Bb Minor", "B Major", "B Minor"],
                            value="Auto",
                            label="Key",
                            elem_classes="dropdown-container",
                        )
                with gr.Group(visible=False) as lyria_settings:
                    gr.Markdown("#### Lyria Tuning")
                    lyria_bpm = gr.Slider(60, 200, 70, step=1, label="BPM")
                    with gr.Row():
                        lyria_density = gr.Slider(0, 1.0, 0.1, step=0.05, label="Density")
                        lyria_brightness = gr.Slider(0, 1.0, 0.15, step=0.05, label="Brightness")

                with gr.Group(visible=False) as upload_settings:
                    gr.Markdown("#### Upload Instrumental")
                    uploaded_music = gr.Audio(
                        label="Instrumental File (wav, mp3, flac, ogg, m4a, aiff)",
                        type="filepath",
                        sources=["upload"],
                    )
                    gr.Markdown(
                        "Your file is looped or trimmed to fit the narration, then "
                        "ducked and mastered like the generated engines.",
                        elem_classes="hint-text",
                    )

                gr.Markdown("#### Export")
                with gr.Row():
                    format_radio = gr.Radio(
                        ["wav", "mp3"], value="wav", label="Format",
                        elem_classes="pill-radio",
                    )
                    seed_input = gr.Number(label="Seed", value=0, precision=0)
                with gr.Row():
                    upsample_checkbox = gr.Checkbox(
                        label="Hi-Fi (48 kHz)", value=True,
                        elem_classes="toggle-switch",
                    )
                    stems_checkbox = gr.Checkbox(
                        label="Export Stems", value=False,
                        elem_classes="toggle-switch",
                    )
                stem_separation_checkbox = gr.Checkbox(
                    label="Clean Music (Source Separation)", value=True,
                    elem_classes="toggle-switch",
                )
                with gr.Row():
                    quality_mode_checkbox = gr.Checkbox(
                        label="High Quality (Best-of-3)", value=False,
                        elem_classes="toggle-switch",
                    )
                    stereo_output_checkbox = gr.Checkbox(
                        label="Stereo Output", value=False,
                        elem_classes="toggle-switch",
                    )
                reference_audio = gr.Audio(
                    label="Style / Melody Reference",
                    type="filepath",
                    sources=["upload"],
                )

    # ── Visibility Callbacks ───────────────────────────────────────────────

    def toggle_mode_settings(mode, current_music_model, current_tts_engine):
        is_inst = mode == "Instrumental Only"
        is_voc = mode == "Vocals Only"
        show_acestep = (current_music_model == "ACE-Step 1.5") and not is_voc
        show_lyria = (current_music_model == "Lyria RealTime") and not is_voc
        show_upload = (current_music_model == "Upload File") and not is_voc
        show_kokoro = (current_tts_engine == "Kokoro") and not is_inst
        show_f5 = (current_tts_engine == "F5-TTS") and not is_inst
        show_indextts = (current_tts_engine == "IndexTTS-2") and not is_inst
        return (
            gr.update(visible=not is_inst),   # script_input
            gr.update(visible=not is_voc),    # music_prompt
            gr.update(visible=is_inst),       # music_duration
            gr.update(visible=show_kokoro),   # kokoro_settings
            gr.update(visible=not is_inst),   # speed_slider
            gr.update(visible=not is_voc),    # duck_slider
            gr.update(visible=not is_inst),   # reverb_slider
            gr.update(visible=not is_voc),    # reference_audio
            gr.update(visible=show_acestep),  # acestep_quality
            gr.update(visible=show_acestep),  # acestep_metadata
            gr.update(visible=show_lyria),    # lyria_settings
            gr.update(visible=show_upload),   # upload_settings
            gr.update(visible=show_f5),       # f5_settings
            gr.update(visible=show_indextts), # indextts_settings
        )

    generation_mode.change(
        fn=toggle_mode_settings,
        inputs=[generation_mode, music_model_dropdown, tts_engine_radio],
        outputs=[script_input, music_prompt, music_duration, kokoro_settings, speed_slider, duck_slider, reverb_slider, reference_audio, acestep_quality, acestep_metadata, lyria_settings, upload_settings, f5_settings, indextts_settings],
    )

    def toggle_music_engine_ui(model, mode):
        is_acestep = model == "ACE-Step 1.5"
        is_lyria = model == "Lyria RealTime"
        is_upload = model == "Upload File"
        is_voc = mode == "Vocals Only"
        return (
            gr.update(visible=is_acestep and not is_voc),  # acestep_quality
            gr.update(visible=is_acestep and not is_voc),  # acestep_metadata
            gr.update(visible=is_lyria and not is_voc),    # lyria_settings
            gr.update(visible=is_upload and not is_voc),   # upload_settings
        )

    music_model_dropdown.change(
        fn=toggle_music_engine_ui,
        inputs=[music_model_dropdown, generation_mode],
        outputs=[acestep_quality, acestep_metadata, lyria_settings, upload_settings],
    )

    def toggle_tts_engine_ui(tts_engine, mode):
        is_inst = mode == "Instrumental Only"
        show_kokoro = (tts_engine == "Kokoro") and not is_inst
        show_f5 = (tts_engine == "F5-TTS") and not is_inst
        show_indextts = (tts_engine == "IndexTTS-2") and not is_inst
        # Set engine-optimal speed default
        if tts_engine == "F5-TTS":
            speed_val = 0.90
            speed_label = "Speech Speed"
        elif tts_engine == "IndexTTS-2":
            speed_val = 1.0
            speed_label = "Speech Speed"
        else:
            speed_val = 0.90
            speed_label = "Speech Speed"
        return (
            gr.update(visible=show_kokoro),
            gr.update(visible=show_f5),
            gr.update(visible=show_indextts),
            gr.update(value=speed_val, label=speed_label),
        )

    tts_engine_radio.change(
        fn=toggle_tts_engine_ui,
        inputs=[tts_engine_radio, generation_mode],
        outputs=[kokoro_settings, f5_settings, indextts_settings, speed_slider],
    )

    generate_btn.click(
        fn=generate_meditation,
        inputs=[
            generation_mode,
            script_input,
            music_prompt,
            music_duration,
            music_model_dropdown,
            kokoro_voice_dropdown,
            speed_slider,
            duck_slider,
            reverb_slider,
            fade_in_slider,
            fade_out_slider,
            format_radio,
            seed_input,
            stems_checkbox,
            upsample_checkbox,
            stem_separation_checkbox,
            reference_audio,
            acestep_quality,
            acestep_bpm,
            acestep_key,
            lyria_bpm,
            lyria_density,
            lyria_brightness,
            tts_engine_radio,
            f5_voice_dropdown,
            f5_wpm_slider,
            reverb_ir_dropdown,
            quality_mode_checkbox,
            stereo_output_checkbox,
            indextts_voice_dropdown,
            indextts_emotion_dropdown,
            indextts_emotion_audio,
            indextts_speed_slider,
            uploaded_music,
        ],
        outputs=[audio_output, status_display],
        show_progress="full",
    )

if __name__ == "__main__":
    # theme, css, and js moved here from gr.Blocks() per Gradio 6.0 API change.
    demo.launch(share=False, theme=theme, css=CUSTOM_CSS, js=DROPDOWN_FIX_JS)
